# Generated by Django 4.2.5 on 2023-09-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="date_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
