# Generated by Django 4.2.5 on 2023-09-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_productprice_date_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="products.product",
            ),
        ),
    ]
